mzhang9622/Mailroom-Flask-App

contact.html, index.html, login.html, style.css
- Edited login.html: adjusted style.css to fix some sizing issue of the login buttons. Fixed some id/class code-smells (not completely fixed)
- Edited contact.html: added a form template that can be linked to an email at some point. Preferably the mailroom's.
- Created reset.html for password/login reset purposes (not priority)
=> second commit: edited login.html, contact.html.

README.md, static/style.css, templates/contact.html, templates/login.html
**Changelog
- Updated README.md
- Updated contact.html, login.html, and style.css
=> New feature

procfile
Pushing in a procfile for heroku
=> adding procfile for heroku

static/style.css, templates/about.html
I made an initial design for the about page using html and css. I am open to suggestions for improvements, and more detail will be added once the mail room employee information is collected.
=> Initial About Page features implemented in html and css

README.md, static/style.css, templates/index.html, templates/reset.html, views.py
Fixed the design for the barcode, such that it only shows on the admin page. Additionally, created the reset page in order for admins to reset their password, when necessary.
=> Updated barcode and create Reset designs

templates/index.html
Messed up the previous push, this redoes everything I undid.
New backend features for admins:
- Admins can add new box data, including upload images.
- Admins can delete box data from inventory.
- Admins can add new admins (emails must end in @colby.edu)
- CSV reader is no longer necessary.
Small issues:
- Flash messages/warnings were implemented but not showing up, not sure if that's just on my end.
- New forms/buttons are not formatted yet.
=> Added ability to add/delete box and add admins

static/style.css
I corrected a formatting mistake that was actually present in the web version but more noticeable in mobile view. Issue has been resolved so that there is no longer white space to the right of the screen.
=> Fixed bugs to make the website compatible with phones and other devices

templates/about.html, templates/admin.html, templates/contact.html, templates/index.html, views.py
As requested, changed 'Settings' tab to 'Admin,' for better clarity and consistency.
=> Changed Settings to Admin for Table of Contents

static/style.css
Fixed some styling issues with how the boxes were demonstrated (e.g fixed the title and images for the boxes when media size gets smaller)
=> Fixed font sizes for boxes for media sizes

views.py, website_test.py
I've added more test cases, especially for the button for adding boxes. I found that the system will crash if you input a very large number of boxes to be added. This needs to be fixed.
=> Added more tests for the box increase button

static/style.css, templates/contact.html
The contact page now has a small header so the page is not just the form.
=> Added contact header

auth.py, models.py, views.py, website.py, website_test.py
Updated code based on PyLint Errors, these include:
- trailing whitespaces
- docstrings
- ordering of import statements
- identations
- new lines
- length of lines
website_test.py was not completed updated according to pylint as a result of the tests not fully done. As a result, majority of the points are loss from pyLint because of this.
However, the score should be around ~80%, which is 2 points more than first run of Pylint, considering a big improvement.
=> Code enhancement according to Pylint

.env, requirements.txt, util.py, views.py
Adding the feature of an email notification when stocks are low. Uses an API from Sendgrid.
=> Email notification

.env, views.py
Changed email that notifications would be sent to.
=> Hiding API key

auth.py, views.py, website_test.py
This is the test code with the old login method. Will need to be revised later on.
=> Finished testing with old login method

auth.py, website_test.py
Updated test code so that it works with either Google's API for login or our own login system. Two of the tests still fail for some reason I am still trying to figure out, and 2 more of the tests fail for intentional reasons, namely 1) that we are hard-coded into the system so I cannot delete any admins currently and 2) the box database is empty so I cannot delete any. These will be tested at the appropriate time. I also had to edit the auth.py file, because I was always being redirected to the login page instead of the main page.
=> Updates to test code to work with either our login system or Google's

website/views.py
No big changes, just rearranging the order of the views for easier navigation.
=> Reorganizing views order

website/static/style.css, website/templates/login.html
Login button was disordered, therefore adjusted the design of the button.
=> fixed login styling issue

website/static/script.js, website/static/style.css, website/templates/index.html, website/views.py
Added extra buttons to the home page that let admins edit the size, link, low stock number, and barcode for each box.
=> Added more update box options

website/static/style.css, website/templates/admin.html
Resolved the white space issue with the background for Admin page when the screen size becomes smaller.
=> Fixed background for admin page

website/static/script.js
There is now a warning for deleting a box similar to deleting admin
=> Added warning for deleting box

test/conftest.py, test/website_test.py, website/auth.py, website/templates/login.html, website/views.py
Getting rid of the Google Auth because of issues. Also making DeAnna the only hard-coded admin, and directing low-stock emails to her.
=> Removing google auth and adding DeAnna to admin

app.py, test/conftest.py, test/website_test.py, website/__init__.py, website/views.py
Updated Pylint score to be above 9/10, additionally, added new folders for testing in terms of organization.
=> Continued to Update Pylint Score

website/__init__.py
Last pull request had an issue with the init file, restoring it to previous version.
=> Undoing edits to init
